language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: hhvm
    allow_failures:
        - php: hhvm

install:
    - composer install --prefer-source
