services:
    entity_tracker.resolver.blamable:
        class: Hostnet\Component\EntityBlamable\Resolver\BlamableResolver
        arguments:
            - "@entity_tracker.provider.annotation_metadata"

    entity_tracker.listener.blamable:
        class: Hostnet\Component\EntityBlamable\Listener\BlamableListener
        arguments:
            - "@entity_tracker.resolver.blamable"
            - "" # provider id, (configurable)
        tags:
            - { name: doctrine.event_listener, event: entityChanged, priority: 32, method: onEntityChanged }

    entity_tracker.provider.blamable:
        class: Hostnet\Bundle\EntityTrackerBundle\Services\Blamable\DefaultBlamableProvider
        arguments:
            - "@security.token_storage"
            - "" # It is being injected by the Extension
